# -*- coding: utf-8 -*-
"""python projects.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JcHvR4ZFhstMO2RJbWfRKRLUQTMmEP7S

CODE TO MAKE FORM
"""

from tkinter import*
root=Tk()
root.maxsize(height=600,width=800)
root.minsize(height=500,width=500)
root.title("Form")
var1=IntVar()
var2=IntVar()
var3=IntVar()
var=IntVar()
var4=StringVar()
var4.set("--select--")
def show():
    a=b2.get()
    print(a)
    b=b4.get()
    print(b)
    c=var1.get()
    d=var2.get()
    e=var3.get()
    course=" "
    if (c==1):
        course+=("c")
    if (d==1):
        course+=("java")
    if(e==1):
        course+=("python")
    print(course)    
    f=var.get()
    if(f==2):
        print("Male")
    else:
        print("Female")
    g=var4.get()
    print(g)
    h=r6.get()
    print(h)
    i=a2.get(0.0,"end-1c")
    print(i)
def show1(): #to reset
    b2.delete(0,END)
    b4.delete(0,END)
    var1.set(" ")
    var2.set(" ")
    var3.set(" ")
    var.set(" ")
    r6.delete(0,END)
    a2.delete(0.0,END)
def show2(): #to exit
    root.destroy()
b1=Label(root,text="Name:",fg='red',font=8)
b1.place(x=40,y=50)
b2=Entry(root,text="")# not to provide space between double quotation
b2.place(x=100,y=50)
b3=Label(root,text="Roll:")
b3.place(x=40,y=80)
b4=Entry(root,text="")
b4.place(x=100,y=80)
b5=Label(root,text="Course:")
b5.place(x=40,y=110)
b6=Checkbutton(root,text="C",variable=var1)
b6.place(x=100,y=110)
b7=Checkbutton(root,text="Java",variable=var2)
b7.place(x=140,y=110)
b8=Checkbutton(root,text="Python",variable=var3)
b8.place(x=195,y=110)
b9=Label(root,text="Gender:")
b9.place(x=40,y=140)
r1=Radiobutton(root,text="Male",variable=var,value=2)
r1.place(x=100,y=140)
r2=Radiobutton(root,text="Female",variable=var,value=3)
r2.place(x=180,y=140)
r3=Label(root,text="Department:")
r3.place(x=40,y=170)
r4=OptionMenu(root,var4,"ECE","CSE","IT","CIVIL")
r4.place(x=120,y=170)
r5=Label(root,text="Marks:")
r5.place(x=40,y=220)
r6=Entry(root,text="")
r6.place(x=100,y=220)
a1=Label(root,text="Adress:")
a1.place(x=40,y=250)
a2=Text(root)# to increase the size of box
a2.place(x=100,y=250, height=100,width=200)
r7=Button(root,text="Submit",command=show)
r7.place(x=40,y=400)
r8=Button(root,text="Reset",command=show1)
r8.place(x=120,y=400)
r9=Button(root,text="Exit",command=show2)
r9.place(x=200,y=400)

"""CODE TO MAKE CALCULATOR"""



from tkinter import*
root=Tk()
root.maxsize(height=500,width=800)
root.minsize(height=320,width=260)
root.title("Form")
var=StringVar()
e=""
def show(a):
    print(a)
    global e
    e=e+str(a)
    print(e)
    var.set(e)
def test():
    global e
    e=" "
    var.set(e)
def calc():
    global e
    e=str(eval(e))
    var.set(e)
a1=Entry(root,text="",font=8,textvariable=var)
a1.place(x=40,y=80)
b1=Button(root, text="7",font=8,bg="grey",bd=5,padx=0.7,pady=0.7,command=lambda:show(7))
b1.place(x=40,y=120)
b2=Button(root, text="8",font=8,bg="grey",bd=5,padx=0.7,pady=0.7,command=lambda:show(8))
b2.place(x=85,y=120)
b3=Button(root, text="9",font=8,bg="grey",bd=5,padx=0.7,pady=0.7,command=lambda:show(9))
b3.place(x=130,y=120)
b4=Button(root, text="6",font=8,bg="grey",bd=5,padx=0.7,pady=0.7,command=lambda:show(6))
b4.place(x=40,y=170)
b5=Button(root, text="5",font=8,bg="grey",bd=5,padx=0.7,pady=0.7,command=lambda:show(5))
b5.place(x=85,y=170)
b6=Button(root, text="4",font=8,bg="grey",bd=5,padx=0.7,pady=0.7,command=lambda:show(4))
b6.place(x=130,y=170)
b7=Button(root, text="3",font=8,bg="grey",bd=5,padx=0.7,pady=0.7,command=lambda:show(3))
b7.place(x=40,y=220)
b8=Button(root, text="2",font=8,bg="grey",bd=5,padx=0.7,pady=0.7,command=lambda:show(2))
b8.place(x=85,y=220)
b9=Button(root, text="1",font=8,bg="grey",bd=5,padx=0.7,pady=0.7,command=lambda:show(1))
b9.place(x=130,y=220)
b10=Button(root, text="+",font=8,bg="grey",bd=5,padx=0.7,pady=0.7,command=lambda:show("+"))
b10.place(x=175,y=120)
b11=Button(root, text="-",font=8,bg="grey",bd=5,padx=0.7,pady=0.7,command=lambda:show("-"))
b11.place(x=175,y=170)
b12=Button(root, text="*",font=8,bg="grey",bd=5,padx=0.7,pady=0.7,command=lambda:show("*"))
b12.place(x=175,y=220)
b13=Button(root, text="/",font=8,bg="grey",bd=5,padx=0.7,pady=0.7,command=lambda:show("/"))
b13.place(x=175,y=270)
b14=Button(root, text="c",font=8,bg="grey",bd=5,padx=0.7,pady=0.7,command=test)
b14.place(x=40,y=270)
b15=Button(root, text="0",font=8,bg="grey",bd=5,padx=0.7,pady=0.7,command=lambda:show(0))
b15.place(x=85,y=270)
b16=Button(root, text="=",font=8,bg="grey",bd=5,padx=0.7,pady=0.7,command=calc)
b16.place(x=130,y=270)

"""CODE TO MAKE CALCULATOR"""

from tkinter import*
root=Tk()
root.maxsize(height=500,width=800)
root.minsize(height=500,width=500)
root.title("Form")
def show():
    a=b2.get()
    print(a)
    b=b4.get()
    print(b)
    c=int(a)+int(b)
    b6.insert(0,c)
def show1():
    a=b2.get()
    print(a)
    b=b4.get()
    print(b)
    d=int(a)-int(b)
    b6.insert(0,d)
def show2():
    a=b2.get()
    print(a)
    b=b4.get()
    print(b)
    e=int(a)*int(b)
    b6.insert(0,e)
def show3():
    a=b2.get()
    print(a)
    b=b4.get()
    print(b)
    f=int(a)*int(b)
    b6.insert(0,f)
def show4(): #to reset
    b2.delete(0,END)
    b4.delete(0,END)
    b6.delete(0,END)
def show5(): #to exit
    root.destroy()    
b1=Label(root,text="First No.",fg='red',font=8)
b1.place(x=40,y=50)
b2=Entry(root,text="")
b2.place(x=120,y=50)
b3=Label(root,text="Second No.",fg='red',font=8)
b3.place(x=40,y=80)
b4=Entry(root,text="")
b4.place(x=130,y=80)
r1=Button(root,text="+",command=show)
r1.place(x=40,y=120)
r2=Button(root,text="-",command=show1)
r2.place(x=70,y=120)
r3=Button(root,text="*",command=show2)
r3.place(x=100,y=120)
r4=Button(root,text="/",command=show3)
r4.place(x=130,y=120)
b5=Label(root,text="Result:",fg='red',font=8)
b5.place(x=40,y=150)
b6=Entry(root,text="")
b6.place(x=100,y=150)
r5=Button(root,text="Clear",command=show4)
r5.place(x=40,y=200)
r6=Button(root,text="Exit",command=show5)
r6.place(x=80,y=200)